### ISSUE TITLE
BHoM_Adapter: review the config input for the PullTo component

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Adapter#125]
In the PullTo method, config is not passed to the push, but to the pull.
Is this the intended behaviour? 
In case so, is there a way to pass the config to the push?

**Comment by alelom** [comment]
I'm not sure it's intended -- honestly I thought it was passed to the Push part (destination) rather than to the Pull part (origin) as it would make more sense: we have more config options with regards to the Push (e.g. ReplaceDependencies, CreateOnly, etc) while I'm not sure there are any config options for the Pull at all.

I guess the correct way to deal with this would be to have two config inputs.
