### ISSUE TITLE
BHoMAdapter is neither a BHoMObject or an IObject?

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Adapter#131]
Is there any framework reason why the `BHoMAdapter` is neither one or the other?

This creates problems at the UI level, since `BHoMAdapter` cannot be held by none of our parameters/goos.

**Comment by alelom** [comment]
From a framework perspective, I believe everything we have in BHoM should be either `IObject` or `IBHoMObject`.

I think that the Adapter should be at least an `IObject`.

**Comment by FraserGreenroyd** [comment]
@adecler is the best person to give a final say as the Framework Lead, but my understanding would be similar to @alelom at this stage.

**Comment by adecler** [comment]
This is because an adapter is neither of those two as it doesn't follow any of the coding style or compliance requirement associated to them.

**Comment by al-fisher** [comment]
What is the current requirements for an object to implement `IObject`?

I do think this is an interesting thread - as how is a `BHoMAdapter` currently handling things like its own serialisation to Json? Is this through exception?

Might there be validity in there being a common parent interface that the `BHoMAdpater` also implements?

**Comment by al-fisher** [comment]
I am thinking it could actually be very helpful, as well as potentially clearer, to extend the remit of `IObject` across all parents including `BHoMAdapter`  And where needed
Perhaps also renaming to `IBHoM`
This might help with indicating those that are actual _BHoM_Objects_ in an `oM` and those simply in the BHoM ecosystem.

**Comment by alelom** [comment]
> I am thinking it could actually be very helpful, as well as potentially clearer, to extend the remit of `IObject` across all parents including `BHoMAdapter` And where needed
> Perhaps also renaming to `IBHoM`
> This might help with indicating those that are actual _BHoM_Objects_ in an `oM` and those simply in the BHoM ecosystem.

I agree on this.

**Comment by alelom** [comment]
To further clarify the current strategy:
![image](https://user-images.githubusercontent.com/6352844/72279920-157b8200-362f-11ea-8424-a53a1b6f99f8.png)

Current version of diagram can be found [here](https://burohappold.sharepoint.com/:f:/s/BHoM/EoZwjG8IubtMh7fMPLN2Y1sBTckuuDIeKmNopQpfiEJXVQ?e=wQwNf2).

**Comment by epignatelli** [comment]
I think this means that we also need a `IBHoMAdapter` goo and parameter in the Grasshopper_Toolkit if we decide to solve https://github.com/BHoM/Grasshopper_Toolkit/issues/365 (which I don't think there is a problem with)

**Comment by adecler** [comment]
Since we are starting a new quarter, it might be worth capturing a conversation I had with Alessio a while ago:

The adapters are not following the same conventions imposed by the framework on oM vs Engine. Indeed, they are your typical OOP style objects with the usual mashup of properties and methods as well as encapsulation of private variables. 

This was the reason why they were not treated as neither BHoMObject nor IObject. They can not be serialised for example because they contain more than just public properties.

I think that we should be eating our own dog food when it comes to preaching for the oM-Engine framework though. This means turning the adapters themselves into compliant BHoM objects that contain only public properties. The methods they currently contain (Pull, Push,...) should be into an Engine. We just need to have those methods taking a `this IAdapter` as first input. This is a serious refactoring so probably something that needs to be designed and strategised during one quarter and actioned at the beginning of the next one. With that in mind, this quarter would be ideal for the planning phase.

**Comment by adecler** [comment]
Closing as this discussion has been stale for a few years. Will re-open if it becomes relevant again
